---
title: "Meta-analysis Study Map - Outdoor air pollution and development of adult asthma (rev. 2024.03.11)"
author: "Spencer Lee"
date: "03/11/2024"
format:
  html:
    code-fold: false
editor: 
  markdown: 
    wrap: 72
---

# Importing dependencies: tmap, rnaturalearth, and rnaturalearthdata
```{r}
 
library(tmap)
library(rnaturalearth)
library(rnaturalearthdata)
```


# World map visualizations (study level country representation)
```{r}
# Importing csv file
world_study <- read.csv(here("data", "world_study.csv"), header = T, sep = ",")

# Counting countries for each row, and then merging with world data
country_count <- as.data.frame(table(world_study$Setting))
colnames(country_count) <- c("country", "study_count")
world_1 <- merge(world, country_count, by.x = "name", by.y = "country", all.x = TRUE)

study_palette <- colorRampPalette(c("lightblue", "blue"))(5)

# Generate map
tmap_mode("plot")
tmap_style("white")
world_studies <- tm_shape(world_1) +
  tm_fill(col = "study_count", 
          palette = study_palette, 
          style = "fixed", breaks = c(1,2,3,4,5),
          legend.show = TRUE,
          title = "Study Count") +
          tm_borders(col = "grey", lwd = 0.5)
world_studies

# Saving map as svg file
tmap_save(world_studies, "world_studies.svg", device = svglite::svglite)
```